/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiExtractRouteImport } from './routes/api/extract'
import { Route as ApiDownloadsRouteImport } from './routes/api/downloads'
import { Route as ApiDownloadRouteImport } from './routes/api/download'
import { Route as ApiDownloadsCompletedRouteImport } from './routes/api/downloads/completed'
import { Route as ApiDownloadDownloadIdRouteImport } from './routes/api/download/$downloadId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractRoute = ApiExtractRouteImport.update({
  id: '/api/extract',
  path: '/api/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadsRoute = ApiDownloadsRouteImport.update({
  id: '/api/downloads',
  path: '/api/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadRoute = ApiDownloadRouteImport.update({
  id: '/api/download',
  path: '/api/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadsCompletedRoute = ApiDownloadsCompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => ApiDownloadsRoute,
} as any)
const ApiDownloadDownloadIdRoute = ApiDownloadDownloadIdRouteImport.update({
  id: '/$downloadId',
  path: '/$downloadId',
  getParentRoute: () => ApiDownloadRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/download': typeof ApiDownloadRouteWithChildren
  '/api/downloads': typeof ApiDownloadsRouteWithChildren
  '/api/extract': typeof ApiExtractRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/download/$downloadId': typeof ApiDownloadDownloadIdRoute
  '/api/downloads/completed': typeof ApiDownloadsCompletedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/download': typeof ApiDownloadRouteWithChildren
  '/api/downloads': typeof ApiDownloadsRouteWithChildren
  '/api/extract': typeof ApiExtractRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/download/$downloadId': typeof ApiDownloadDownloadIdRoute
  '/api/downloads/completed': typeof ApiDownloadsCompletedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/download': typeof ApiDownloadRouteWithChildren
  '/api/downloads': typeof ApiDownloadsRouteWithChildren
  '/api/extract': typeof ApiExtractRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/download/$downloadId': typeof ApiDownloadDownloadIdRoute
  '/api/downloads/completed': typeof ApiDownloadsCompletedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/download'
    | '/api/downloads'
    | '/api/extract'
    | '/api/auth/$'
    | '/api/download/$downloadId'
    | '/api/downloads/completed'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/download'
    | '/api/downloads'
    | '/api/extract'
    | '/api/auth/$'
    | '/api/download/$downloadId'
    | '/api/downloads/completed'
  id:
    | '__root__'
    | '/'
    | '/api/download'
    | '/api/downloads'
    | '/api/extract'
    | '/api/auth/$'
    | '/api/download/$downloadId'
    | '/api/downloads/completed'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDownloadRoute: typeof ApiDownloadRouteWithChildren
  ApiDownloadsRoute: typeof ApiDownloadsRouteWithChildren
  ApiExtractRoute: typeof ApiExtractRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract': {
      id: '/api/extract'
      path: '/api/extract'
      fullPath: '/api/extract'
      preLoaderRoute: typeof ApiExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/downloads': {
      id: '/api/downloads'
      path: '/api/downloads'
      fullPath: '/api/downloads'
      preLoaderRoute: typeof ApiDownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download': {
      id: '/api/download'
      path: '/api/download'
      fullPath: '/api/download'
      preLoaderRoute: typeof ApiDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/downloads/completed': {
      id: '/api/downloads/completed'
      path: '/completed'
      fullPath: '/api/downloads/completed'
      preLoaderRoute: typeof ApiDownloadsCompletedRouteImport
      parentRoute: typeof ApiDownloadsRoute
    }
    '/api/download/$downloadId': {
      id: '/api/download/$downloadId'
      path: '/$downloadId'
      fullPath: '/api/download/$downloadId'
      preLoaderRoute: typeof ApiDownloadDownloadIdRouteImport
      parentRoute: typeof ApiDownloadRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiDownloadRouteChildren {
  ApiDownloadDownloadIdRoute: typeof ApiDownloadDownloadIdRoute
}

const ApiDownloadRouteChildren: ApiDownloadRouteChildren = {
  ApiDownloadDownloadIdRoute: ApiDownloadDownloadIdRoute,
}

const ApiDownloadRouteWithChildren = ApiDownloadRoute._addFileChildren(
  ApiDownloadRouteChildren,
)

interface ApiDownloadsRouteChildren {
  ApiDownloadsCompletedRoute: typeof ApiDownloadsCompletedRoute
}

const ApiDownloadsRouteChildren: ApiDownloadsRouteChildren = {
  ApiDownloadsCompletedRoute: ApiDownloadsCompletedRoute,
}

const ApiDownloadsRouteWithChildren = ApiDownloadsRoute._addFileChildren(
  ApiDownloadsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDownloadRoute: ApiDownloadRouteWithChildren,
  ApiDownloadsRoute: ApiDownloadsRouteWithChildren,
  ApiExtractRoute: ApiExtractRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
